In [9]:
import pandas as pd

In [10]:
data=pd.read_csv(r"C:\Users\Aryan\Desktop\python\Churn_Modelling.csv")
data.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1.0,0.0,149756.71,1
6,7,15592531,Bartlett,822,NaN,Male,50.0,7,0.00,2,1.0,1.0,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29.0,4,115046.74,4,1.0,0.0,119346.88,1
8,9,15792365,He,501,France,Male,44.0,4,142051.07,2,0.0,NaN,74940.50,0
9,10,15592389,H?,684,France,Male,NaN,2,134603.88,1,1.0,1.0,71725.73,0

In [11]:
new_data=data.drop(["RowNumber","CustomerId","Surname","Geography","Gender"],axis='columns')

In [12]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10002 non-null  int64
 1   Age              10001 non-null  float64
 2   Tenure           10002 non-null  int64
 3   Balance          10002 non-null  float64
 4   NumOfProducts    10002 non-null  int64
 5   HasCrCard        10001 non-null  float64
 6   IsActiveMember   10001 non-null  float64
 7   EstimatedSalary  10002 non-null  float64
 8   Exited           10002 non-null  int64
dtypes: float64(5), int64(4)
memory usage: 703.4 KB

In [13]:
new_data.fillna(method='ffill',inplace=True)

C:\Users\Aryan\AppData\Local\Temp\ipykernel_16488\2418240409.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_data.fillna(method='ffill',inplace=True)

In [14]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10002 non-null  int64
 1   Age              10002 non-null  float64
 2   Tenure           10002 non-null  int64
 3   Balance          10002 non-null  float64
 4   NumOfProducts    10002 non-null  int64
 5   HasCrCard        10002 non-null  float64
 6   IsActiveMember   10002 non-null  float64
 7   EstimatedSalary  10002 non-null  float64
 8   Exited           10002 non-null  int64
dtypes: float64(5), int64(4)
memory usage: 703.4 KB

In [15]:
df=pd.get_dummies(new_data)
new_data.head(10)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,43.0,2,125510.82,1,0.0,1.0,79084.10,0
5,645,44.0,8,113755.78,2,1.0,0.0,149756.71,1
6,822,50.0,7,0.00,2,1.0,1.0,10062.80,0
7,376,29.0,4,115046.74,4,1.0,0.0,119346.88,1
8,501,44.0,4,142051.07,2,0.0,0.0,74940.50,0
9,684,44.0,2,134603.88,1,1.0,1.0,71725.73,0

In [16]:
df.astype(float)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619.0,42.0,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,850.0,43.0,2.0,125510.82,1.0,0.0,1.0,79084.10,0.0
...,...,...,...,...,...,...,...,...,...
9997,709.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58,1.0
9998,772.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52,1.0
9999,772.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52,1.0
10000,792.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78,0.0
10001,792.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78,0.0

In [17]:
df['Balance'].value_counts()

Balance
0.00         3617
130170.82       2
75075.31        2
105473.74       2
130142.79       2
             ...
107499.70       1
98807.45        1
136596.85       1
81556.89        1
148795.17       1
Name: count, Length: 6382, dtype: int64

In [18]:
# df['IsBalanceZero'] = df['Balance'] == 0
# df['MultipleProducts'] = df['NumOfProducts'] > 1
# df['HasCrCard'].value_counts()

In [19]:
df.head(5)
df.astype(float)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619.0,42.0,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,850.0,43.0,2.0,125510.82,1.0,0.0,1.0,79084.10,0.0
...,...,...,...,...,...,...,...,...,...
9997,709.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58,1.0
9998,772.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52,1.0
9999,772.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52,1.0
10000,792.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78,0.0
10001,792.0,28.0,4.0,130142.79,1.0,1.0,0.0,38190.78,0.0

In [20]:
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, accuracy_score

In [25]:
rux= df.drop('Exited', axis='columns') 
ruy= df['Exited']

In [27]:
ru = RandomUnderSampler(random_state=42)
x, y = ru.fit_resample(rux, ruy)

In [29]:
# x['Balance'].value_counts()

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [33]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform it
x_train_scaled = scaler.fit_transform(x_train)

# Transform the test data
x_test_scaled = scaler.transform(x_test)

In [35]:
rfc=RandomForestClassifier(max_depth=6, min_samples_leaf=5, min_samples_split=10)
rfc.fit(x_train_scaled,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=5, min_samples_split=10)

In [36]:
rfc.score(x_test_scaled,y_test)

0.7622549019607843

In [39]:
y_predict = rfc.predict(x_test_scaled)
y_pred=rfc.predict(x_train_scaled)

In [41]:
test_a = accuracy_score(y_test,y_predict)
train_a = accuracy_score(y_train,y_pred)
print("test_accuracy",test_a)
print("train_accurary",train_a)

test_accuracy 0.7622549019607843
train_accurary 0.7840490797546013

In [43]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test, y_predict)
cm

array([[351,  92],
       [102, 271]], dtype=int64)

In [45]:
precision = precision_score(y_test, y_predict)
recall = recall_score(y_test, y_predict)
print("recall:",recall)
print("precision:", precision)

recall: 0.7265415549597856
precision: 0.7465564738292011

In [47]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_predict)
f1

0.7364130434782609

In [49]:
# from sklearn.model_selection import cross_val_score

# cv_scores = cross_val_score(rfc_best, x, y, cv=5)
# print(f'Cross-Validation Scores: {cv_scores}')
# print(f'Mean CV Score: {cv_scores.mean()}')

In [ ]:
# from sklearn.model_selection import GridSearchCV

# param_grid = {
#     'n_estimators': [100, 200, 300],
#     'max_depth': [None, 10, 20, 30],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4]
# }
# grid_search = GridSearchCV(estimator=rfc, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
# grid_search.fit(x_train, y_train)

# print(f'Best Parameters: {grid_search.best_params_}')

In [ ]:
# best_params = grid_search.best_params_
# rfc_best = RandomForestClassifier(**best_params) 
# rfc_best.fit(x_train, y_train)

In [ ]:
# rfc_best = RandomForestClassifier(**best_params) 
# rfc_best.fit(x_train, y_train)
# rfc.score(x_test,y_test)

In [ ]:
# y_predict = rfc_best.predict(x_test) 
# y_pred = rfc_best.predict(x_train)

In [ ]:
# test_a = accuracy_score(y_test, y_predict) 
# train_a = accuracy_score(y_train, y_pred) 
# print(f'Test Accuracy: {test_a}') 
# print(f'Train Accuracy: {train_a}')

In [ ]:
# precision = precision_score(y_test, y_predict) 
# recall = recall_score(y_test, y_predict) 
# f1 = f1_score(y_test, y_predict) 
# print(f'Precision: {precision}') 
# print(f'Recall: {recall}') 
# print(f'F1 Score: {f1}')

In [ ]:
# importances = rfc_best.feature_importances_
# feature_names = x_train.columns
# feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# print(feature_importance_df)

In [ ]:
# from sklearn.model_selection import cross_val_score

# # Initialize the Random Forest model with the best parameters
# rfc_best = RandomForestClassifier(max_depth=10, min_samples_leaf=4, min_samples_split=5, n_estimators=100)

# # Perform cross-validation
# cv_scores = cross_val_score(rfc_best, x, y, cv=5)

# # Print cross-validation scores
# print(f'Cross-Validation Scores: {cv_scores}')
# print(f'Mean CV Score: {cv_scores.mean()}')